version: '3.8'

services:
  app:
    image: php:8.0-fpm
    container_name: app
    working_dir: /var/www
    volumes:
      - ./app:/var/www
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www
    depends_on:
      - app
    networks:
      - laravel

networks:
  laravel:
    driver: bridge