version: '3.7'

services:
  app:
    image: php:8.0-fpm
    container_name: projeto_teste_app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: projeto_teste_nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf  # Certifique-se de que o arquivo de configuração do Nginx está correto
    depends_on:
      - app
    networks:
      - laravel

networks:
  laravel:
    driver: bridge